name: github-actuin
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Node modules installation
        run: npm install
      - name: Build project
        run: npm run build
      - name: Sets the vercel env
        run: |
          cd build
          mkdir .vercel
          touch project.json
          echo '{"orgId":"cQWqxIsW3NgivhQwl00umIpf","projectId":"prj_EJ5IfRJv9vKTkEDGaK5PdarVJSA5"}' > project.json
      - name: Deploying the project
        run: npm run deploy
