name: github-actuin
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Node modules installation
        run: npm install
      - name: Build project
        run: npm run build
      - name: Deploying the project
        env:
          VERCEL_ORG_ID: cQWqxIsW3NgivhQwl00umIpf
          VERCEL_PROJECT_ID: prj_EJ5IfRJv9vKTkEDGaK5PdarVJSA5
        run: npm run deploy
