name: github-actuin
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.final-step.outputs.text }}
    env: 
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'
      - name: Node modules installation
        run: npm install
      - name: Build project
        run: npm run build
      - name: Set the vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo "{\"orgId\":\"$VERCEL_PROJECT_ID\",\"projectId\":\"VERCEL_ORG_ID\"}"
      - name: Deploying the project
        run: npm run deploy
      - name: Setup finish
        id: final-step
        run: echo "::set-output name=text::build-job-is-done"
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    env: 
      MY_JOB_OUTPUT: ${{ needs.build-app.outputs.text }}
    steps:
      - run: echo "Test"
      - run: echo $MY_JOB_OUTPUT